#pragma once

//Adapted from glfw3.h

#define CHROMA_MOUSE_BUTTON_1         0
#define CHROMA_MOUSE_BUTTON_2         1
#define CHROMA_MOUSE_BUTTON_3         2
#define CHROMA_MOUSE_BUTTON_4         3
#define CHROMA_MOUSE_BUTTON_5         4
#define CHROMA_MOUSE_BUTTON_6         5
#define CHROMA_MOUSE_BUTTON_7         6
#define CHROMA_MOUSE_BUTTON_8         7
#define CHROMA_MOUSE_BUTTON_LAST      CHROMA_MOUSE_BUTTON_8
#define CHROMA_MOUSE_BUTTON_LEFT      CHROMA_MOUSE_BUTTON_1
#define CHROMA_MOUSE_BUTTON_RIGHT     CHROMA_MOUSE_BUTTON_2
#define CHROMA_MOUSE_BUTTON_MIDDLE    CHROMA_MOUSE_BUTTON_3