# This is a basic workflow to help you get started with Actions

name: Weekly Builds

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install/Verify python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
          
      - name: Cache Vulkan SDK
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: "C:\\VulkanSDK\\1.2.170.0"
          key: vulkan-sdk-1.2.170.0
          
          
      - name: Setup Vulkan
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.170.0/windows/VulkanSDK-1.2.170.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Run bat script on PowerShell
        shell: pwsh
        run: ./third_party/premake-core/bin/release/premake5.exe vs2019
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Build Polychrome
        run: msbuild Polychrome/Polychrome.vcxproj -p:Configuration=Debug -p:Platform=x64
        
        
