# This is a basic workflow to help you get started with Actions

name: Weekly Builds

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install/Verify python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.3
        with:
          vulkan-version: 1.2.170.0
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Run bat script on PowerShell
        shell: pwsh
        run: ./third_party/premake-core/bin/release/premake5.exe vs2019
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Build Polychrome
        run: msbuild Polychrome/Polychrome.vscproj -p:Configuration=Debug
        
        
